[bm]
    [bm.server]
        addr = "0.0.0.0:1240"
        timeout = "1s"
    [bm.client]
        key = "c8c48e784e05acfb"
        secret = "aa63ee0a10afa358d02a07e7abcec546"
        dial = "10000ms"
        timeout = "300s"
        keepAlive = "600s"
        timer = 100
    [bm.client.breaker]
        window  = "30s"
        sleep   = "1000ms"
        bucket  = 10
        ratio   = 0.5
        request = 100
